Repository googleapis/python-os-config, pull requests merged in 2021-04, with the labels that each got.

#55 chore: start tracking obsolete files
  synth.metadata
Labels: api: osconfig, cla: yes, context: full

#46 feat: release as GA
  .repo-metadata.json
  README.rst
  setup.py
Labels: api: osconfig, automerge, cla: yes

#57 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#58 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: osconfig, cla: yes, context: full, samples

#60 chore: prevent normalization of semver versioning
  setup.py
Labels: api: osconfig, cla: yes

#59 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#61 chore(revert): revert preventing normalization
  setup.py
Labels: api: osconfig, cla: yes
